# Generated by Django 3.0.3 on 2020-03-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serach',
            new_name='Search',
        ),
    ]
