# Generated by Django 3.0.3 on 2020-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200312_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='dupa'),
            preserve_default=False,
        ),
    ]
